### ISSUE TITLE
LEMP Bash Server IP

### ISSUE THREAD

**Issue by anazhd** [aymjnd/eNgenie#1]
```bash
###Get IP/domain server 
echo -n "Enter your Server IP or domain and press [ENTER]: "
read IP
```
Can be like this for automation
```bash
###Get IP/domain server
IP=$(curl -4 icanhazip.com)
```

**Comment by anazhd** [comment]
Hold. Will think about how to do this with domain. Didn't think that through.

**Comment by notsuhz** [comment]
You don't need to specify the public IP in the conf, if the server only has one public IP. why bother :-)
